class Constants:
    PERSON = 'PERSON'
    ADDRESS = 'ADDRESS'

    FIRST_NAME = 'first_name'
    MIDDLE_NAME = 'middle_name'
    LAST_NAME = 'last_name'
    FULL_NAME = 'full_name'
    TITLE = 'title'
    TAX_ID = 'tax_id'
    AGE = 'age'
    BIRTH_DATE = 'birth_date'
    GENDER = 'gender'
    NAT = 'nat'
    USERNAME = 'username'
    PASSWORD = 'password'

    STREET = 'street'
    CITY = 'city'
    STATE = 'state'
    POSTAL_CODE = 'postal_code'
    COUNTRY = 'country'
    HOME_PHONE = 'home_phone'
    MOBILE_PHONE = 'mobile_phone'
    EMAIL = 'email'
    LATITUDE = 'latitude'
    LONGITUDE = 'longitude'

