class Constants:
    person = 'PERSON'
    party = 'PARTY'
    contact = 'CONTACT'
    address = 'ADDRESS'

    first_name = 'FIRSTNAME'
    middle_name = 'MIDDLENAME'
    last_name = 'LASTNAME'
    full_name = 'FULLNAME'
    alias = 'ALIAS'
    maiden_name = 'MAIDENNAME'
    mothers_maiden_name = 'MOTHERSMAIDENNAME'
    title = 'TITLE'
    prefix = 'PREFIX'
    suffix = 'SUFFIX'
    tax_id = 'TAXID'
    birth_date = 'BIRTHDATE'
    death_date = 'DEATH_DATE'
    gender = 'GENDER'

    street1 = 'STREET1'
    street2 = 'STREET2'
    city = 'CITY'
    state = 'STATE'
    postal_code_prefix = 'POSTALCODEPREFIX'
    postal_code_suffix = 'POSTALCODESUFFIX'
    country = 'COUNTRY'
    home_phone = 'HOMEPHONE'
    work_phone = 'WORKPHONE'
    mobile_phone = 'MOBILEPHONE'
    pager = 'PAGER'
    fax = 'FAX'
    email = 'EMAIL'
    secondary_email = 'SECONDARYEMAIL'
    county = 'COUNTY'
    latitude = 'LATITUDE'
    longitude = 'LONGITUDE'

