class Constants:
    person = 'PERSON'
    address = 'ADDRESS'

    first_name = 'FIRSTNAME'
    middle_name = 'MIDDLENAME'
    last_name = 'LASTNAME'
    full_name = 'FULLNAME'
    title = 'TITLE'
    tax_id = 'TAXID'
    birth_date = 'BIRTHDATE'
    death_date = 'DEATH_DATE'
    gender = 'GENDER'

    street = 'STREET'
    city = 'CITY'
    state = 'STATE'
    postal_code = 'POSTALCODE'
    country = 'COUNTRY'
    home_phone = 'HOMEPHONE'
    mobile_phone = 'MOBILEPHONE'
    email = 'EMAIL'
    latitude = 'LATITUDE'
    longitude = 'LONGITUDE'

